version: "3.1"
services:
  # DB
  go-todo-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

  # Api
  go-todo-api:
    container_name: go-todo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    tty: true
    env_file:
      - .go_env
    environment:
      - TZ=Asia/Tokyo
    # command: ["/app/go_todo_api"]
    depends_on:
      - go-todo-mysql

volumes:
  mysql-data:
